# Generated by Django 3.2.5 on 2021-08-04 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='course',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='section',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='session',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='year',
        ),
    ]
